import React from 'react';
import {
  AbsoluteFill,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  Sequence,
} from 'remotion';
import { AnimatedChart } from '../components/AnimatedChart';
import { MetricCard } from '../components/MetricCard';

const COLORS = {
  bg: '#0A0B14',
  primary: '#00D4AA',
  secondary: '#7B61FF',
  accent: '#FF6B6B',
  text: '#FFFFFF',
  textMuted: '#8B8D97',
  card: '#151623',
};

// Real backtest results — GA-optimized (60pop × 40gen, 500 days Nov 2024 – Mar 2026)
// Generated by packages/backtest/src/simulator.py
const SAMPLE_EQUITY = [
  99.83, 101.72, 103.03, 104.10, 105.48, 106.74, 107.32, 107.53, 107.77, 108.17,
  108.46, 108.84, 109.25, 109.59, 109.94, 110.32, 110.71, 111.04, 111.42, 111.78,
  112.09, 112.43, 112.76, 113.02, 113.27, 113.51, 113.74, 113.98, 114.17, 114.35,
  114.52, 114.68, 114.82, 114.87, 114.84, 114.79, 114.73, 114.68, 114.65, 114.62,
  114.60, 114.59, 114.62, 114.65, 114.68, 114.71, 114.73, 114.75, 114.77, 114.78,
  114.79, 114.80, 114.81, 114.82, 114.83, 114.84, 114.85, 114.86, 114.87, 114.88,
  114.88, 114.88, 114.88, 114.88, 114.88, 114.88, 114.88, 114.88, 114.88, 114.88,
  114.88, 114.88, 114.88, 114.88, 114.88, 114.88, 114.77, 114.81, 114.80, 114.86,
  114.89, 114.89, 114.89, 114.89, 114.89, 114.89, 114.89, 114.89, 114.89, 114.89,
  114.72,
];

// Actual metrics from backtest (GA-optimized, 500 days Nov 2024 – Mar 2026)
const SAMPLE_METRICS = {
  sharpe_ratio: 31.21,
  sortino_ratio: 44.50,
  calmar_ratio: 6.41,
  max_drawdown_pct: 1.70,
  total_return_pct: 14.72,
  annualized_apy_pct: 10.54,
  win_rate: 1.0,
  total_trades: 10,
};

export const BacktestResults: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const titleOpacity = interpolate(frame, [0, 15], [0, 1], {
    extrapolateRight: 'clamp',
  });

  return (
    <AbsoluteFill
      style={{
        backgroundColor: COLORS.bg,
        fontFamily: 'Inter, system-ui, sans-serif',
        padding: 80,
      }}
    >
      {/* Title */}
      <h2
        style={{
          opacity: titleOpacity,
          fontSize: 48,
          fontWeight: 700,
          color: COLORS.text,
          marginBottom: 40,
        }}
      >
        Backtest Results{' '}
        <span style={{ color: COLORS.textMuted, fontSize: 28 }}>
          (500 days • Nov 2024 – Mar 2026 • Bull + Bear)
        </span>
      </h2>

      {/* Equity Curve (0-600 frames = 0-20s) */}
      <Sequence from={0} durationInFrames={600}>
        <div style={{ height: 350, marginBottom: 40 }}>
          <AnimatedChart
            data={SAMPLE_EQUITY}
            color={COLORS.primary}
            label="Equity (USDC)"
            frame={frame}
            animationDuration={300}
          />
        </div>
      </Sequence>

      {/* Metrics Grid (from frame 300 = 10s) */}
      <Sequence from={300} durationInFrames={1050}>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(4, 1fr)',
            gap: 20,
          }}
        >
          <MetricCard
            label="Annualized APY"
            value={`+${SAMPLE_METRICS.annualized_apy_pct.toFixed(2)}%`}
            color={COLORS.primary}
            frame={frame}
            delay={310}
          />
          <MetricCard
            label="Total Return"
            value={`+${SAMPLE_METRICS.total_return_pct.toFixed(2)}%`}
            color={COLORS.primary}
            frame={frame}
            delay={325}
          />
          <MetricCard
            label="Sharpe Ratio"
            value={SAMPLE_METRICS.sharpe_ratio.toFixed(2)}
            color={COLORS.secondary}
            frame={frame}
            delay={340}
          />
          <MetricCard
            label="Max Drawdown"
            value={`${SAMPLE_METRICS.max_drawdown_pct.toFixed(2)}%`}
            color={COLORS.accent}
            frame={frame}
            delay={355}
          />
          <MetricCard
            label="Calmar Ratio"
            value={SAMPLE_METRICS.calmar_ratio.toFixed(2)}
            color={COLORS.secondary}
            frame={frame}
            delay={370}
          />
          <MetricCard
            label="Sortino Ratio"
            value={SAMPLE_METRICS.sortino_ratio.toFixed(2)}
            color={COLORS.primary}
            frame={frame}
            delay={385}
          />
          <MetricCard
            label="Win Rate"
            value={`${(SAMPLE_METRICS.win_rate * 100).toFixed(0)}%`}
            color={COLORS.primary}
            frame={frame}
            delay={400}
          />
          <MetricCard
            label="Total Trades"
            value={SAMPLE_METRICS.total_trades.toString()}
            color={COLORS.textMuted}
            frame={frame}
            delay={415}
          />
        </div>
      </Sequence>
    </AbsoluteFill>
  );
};
